### ISSUE TITLE
the examples can't built after a dependancy change

### ISSUE THREAD

**Issue by sanabel-al-firdaws** [bondiano/telega#19]
it shows me 3 errors related to the glisten package

```gleam
error: Unknown module value
   ┌─ C:\gleam_project\build\packages\glisten\src\glisten\socket\options.gleam:80:22
   │
80 │   |> list.map(dynamic.unsafe_coerce)
   │                      ^^^^^^^^^^^^^^
```
The module `gleam/dynamic` does not have a `unsafe_coerce` value.

in gleam's std v0.40.0 - 2024-08-19 The deprecated dynamic.unsafe_coerce function has been removed.

using windows

**Comment by sanabel-al-firdaws** [comment]
The package `telega` requires a Gleam version satisfying 1.3.0 <= v < 1.4.0 but you are using v1.5.1.


i think this is the problem ig we need to update the package to use glisten v 6 and latest gleam version 1.5

**Comment by sanabel-al-firdaws** [comment]
changing the library toml file to this seems to fix it 

```toml
name = "telega"
version = "0.3.0"
description = "Gleam Telegram Bot Library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bondiano", repo = "telega" }
links = [
    { title = "Issues", href = "https://github.com/bondiano/telega/issues" },
    { title = "Examples", href = "https://github.com/bondiano/telega/tree/master/examples" },
]

# gleam = ">= 0.32.0"
target = "erlang"
dependencies = { gleam_stdlib = ">= 0.40.0 and < 1.0.0", logging = ">= 1.3.0 and < 2.0.0", gleam_http = ">= 3.7.0 and < 4.0.0", gleam_httpc = ">= 3.0.0 and < 4.0.0", wisp = ">= 1.2.0 and < 2.0.0", gleam_json = ">= 2.0.0 and < 3.0.0", gleam_erlang = ">= 0.27.0 and < 1.0.0", gleam_otp = ">= 0.12.1 and < 1.0.0", glisten = ">= 6.0.0 and < 7.0.0" }

[dev-dependencies]
gleeunit = "~> 1.0"
mockth = "0.3.2"

```
